# Generated by Django 3.2 on 2021-04-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('Лекция', 'Theory'), ('Семинар', 'Lab')], max_length=200, null=True),
        ),
    ]
