# Generated by Django 3.2 on 2021-04-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0002_alter_course_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('Theory', 'Лекция'), ('Lab', 'Семинар')], max_length=200, null=True),
        ),
    ]
