# Generated by Django 3.2 on 2021-04-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0004_alter_classroom_classroom_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='available_hours',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
