# Generated by Django 3.2 on 2021-04-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0005_alter_professor_available_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='end_time',
            field=models.PositiveIntegerField(default=21, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='start_time',
            field=models.PositiveIntegerField(default=8, null=True),
        ),
    ]
