# Generated by Django 3.2 on 2021-04-26 22:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0006_auto_20210426_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='week_day',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default=['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'], max_length=2000),
        ),
    ]
